name: CI

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          pip install -r requirements.txt
          # Optional: add test-only deps if you use them
          pip install pytest pytest-httpx responses

      - name: Ruff lint
        run: ruff check .

      - name: Run unit tests (if present)
        shell: bash
        run: |
          if ls **/tests/*_test.py **/tests/test_*.py 1>/dev/null 2>&1; then
            pytest -q
          else
            echo "No tests found, skipping."
          fi

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform fmt (check)
        working-directory: terraform
        run: terraform fmt -check -recursive

      - name: Terraform init (no backend)
        working-directory: terraform
        run: terraform init -backend=false -input=false

      - name: Terraform validate
        working-directory: terraform
        run: terraform validate